//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build-tasks/generatemocks.js)
//----------------------------------------------------
var RecommendationsModule = {
  'models': require('./models'),
  'views': require('./views')
};
module.exports = RecommendationsModule;