//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build-tasks/generatemocks.js)
//----------------------------------------------------
var HomeModule = {
  'router': require('./router'),
  'views': require('./views')
};
module.exports = HomeModule;