//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build/tasks/genpackageindex.js)
//----------------------------------------------------
module.exports = {
  'carousel': require('./carousel'),
  'common': require('./common'),
  'home': require('./home'),
  'projects': require('./projects'),
  'recommendations': require('./recommendations')
};