//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build/tasks/genpackageindex.js)
//----------------------------------------------------
module.exports = {
  'Carousel': require('./Carousel')
};