//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build/tasks/genpackageindex.js)
//----------------------------------------------------
var ProjectsModule = {
  'models': require('./models'),
  'views': require('./views')
};
module.exports = ProjectsModule;