//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build/tasks/genpackageindex.js)
//----------------------------------------------------
module.exports = {
  'Project': require('./Project'),
  'Projects': require('./Projects')
};